services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hamburgueria_backend
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=${PORT}
      - DATABASE_URL=mongodb://mongodb_replica:27017/hamburgueria?directConnection=true
      - CLOUD_NAME=${CLOUD_NAME}
      - API_SECRET=${API_SECRET}
      - API_KEY=${API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hamburgueria_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3333
    depends_on:
      - app

  mongodb:
    image: mongo:8
    container_name: mongodb_replica
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - hamburgueria_mongodb:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
volumes:
  hamburgueria_mongodb:
