services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=3333${PORT}
      - DATABASE_URL=mongodb://mongodb_replica:27017/hamburgueria?directConnection=true
      - CLOUD_NAME=${CLOUD_NAME}
      - API_SECRET=${API_SECRET}
      - API_KEY=${API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    command: npm run dev

  mongodb:
    image: mongo:8
    container_name: mongodb_replica
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - hamburgueria_mongodb:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
volumes:
  hamburgueria_mongodb:
